### ISSUE TITLE
Feature: Add "open in gitpod" in readme

### ISSUE THREAD

**Issue by user-64bit** [open-sauced/hot#168]
### Type of feature

✅ Test

### Current behavior

If someone wants to look at the project and do some try and error things, that can be done using Gitpod.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Hello and thank you for opening the issue! 🍕  This is actually a discussed topic in https://github.com/open-sauced/open-sauced/issues/867 and due to some limitations in the oauth process we cannot use WEB IDEs to test the actual application as the login redirect would either refresh the live website or straight not work. 

With the addition of a backend API we might be able to fix this, however, it's an exploratory step to be taken once we announce the backend integration. Until then, when requiring strictly editing capabilities, our go-to was pressing `.` inside the GitHub domain for a personalized VSC instance. 

If, however, you would like to contribute the "open in GitPod" button with the above limitation somehow explained, we have the markdown code for that available in the [open-sauced README](https://github.com/open-sauced/open-sauced/blob/main/README.md).

**Comment by 0-vortex** [comment]
This can be done now as supabase supports wildcard URLs, however I don't think many people are comfortable making potential necessary changes for all the updates web IDE platforms have received in the last 6 months. 

@bdougie you wanna do this one together, get some open sauced reviews on running the repos in web based development platforms? 🍕
