### ISSUE TITLE
Bug: Broken design on very large screens

### ISSUE THREAD

**Issue by hokagedemehin** [open-sauced/hot#256]
### Describe the bug

On large screens, the nav bar keeps expanding out of their positions. There should be a max width set for the nav bar as we have the same restriction on other contents on the page. Also, the hero's background color should also extend and cover its space just like the hot repositories section

### Steps to reproduce

1. Go to [https://hot.opensauced.pizza/](https://hot.opensauced.pizza/) on a large screen or zoom out on your laptop to 50%
![large screen screenshot](https://user-images.githubusercontent.com/16826624/181515545-e9f24775-becc-4e90-a847-54c44e8f5550.png)

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome, Firefox, Edge

### Environment

Production, Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Very good catch! ❤️

**Comment by NsdHSO** [comment]
I think the designer should to did some change here. Because after you see how it is draw, how is it right now implemented is correct 
![Screenshot 2022-07-28 at 21 52 28](https://user-images.githubusercontent.com/37635083/181615688-327edc5c-6df7-471c-86f1-2a1fe58e936b.png)

I think this issue it is true if @bdougie  decided to go in this diection

**Comment by 0-vortex** [comment]
That gradient should be translated from a SVG into CSS properties or scaled correctly with `background-size: contain` tailwind equivalents! 🍕

**Comment by NsdHSO** [comment]
.take

**Comment by 0-vortex** [comment]
> .take
> 
> 

Hey there, i saw you took on a couple of issues at a time - please assign yourself to the issue you plan on working next, and, if there's anything else you want to do, announce that on the issue and maybe share some knowledge with other interested contributors.

To dismiss an unfair spirit of competition, we only assign 1 unit worth of work at a time and compete towards supporting ongoing contributions - a lot of people are helping out push PRs to their respective targets rather than pursue a contribution graph! 🤌 🍕
