### ISSUE TITLE
Feature: Avatars should be clickable links into profiles 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#29]
### Type of feature

Feature

### Current behavior

These avatars currently are not clickable and provide no context. 

<img width="269" alt="Screen Shot 2021-12-22 at 9 00 03 AM" src="https://user-images.githubusercontent.com/5713670/147104403-86e80b57-dfd5-4379-b980-e589efbff064.png">
 

### Desired solution

Similar to the title link, these be click github.com links to the user github profile. 

![linkable-avi](https://user-images.githubusercontent.com/5713670/147105682-1a6d78b2-8ce0-4b94-bdf3-caebdf534f78.png)

### Additional context

This should be a dynamic and reusable solution.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frankiefab100** [comment]
Let me work on it

**Comment by jasonericdavis** [comment]
Thanks for taking this on @frankiefab100  Please review the [CONTRIBUTING.md](https://github.com/open-sauced/.github/blob/09ed85f8482c392af87d76b356bf98f2aee1eeaa/CONTRIBUTING.md#issues) for info on how to assign yourself to the issue

**Comment by frankiefab100** [comment]
@jasonericdavis please where can I locate this issue?

**Comment by jasonericdavis** [comment]
I am unsure what you are asking

**Comment by frankiefab100** [comment]
I mean I can navigate to the avatar directory

**Comment by bdougie** [comment]
There is not a directory, the API pulls in the login (i.e. bdougie). You can leverage the login to get the [avatar url](https://stackoverflow.com/questions/22932422/get-github-avatar-from-email-or-name)

**Comment by jasonericdavis** [comment]
@frankiefab100 There isn't explicitly an avatar directory. This issue is to add functionality to the avatars on the cards in the list.  The avatars can be found in the following files:

- src/components/PostGrid.jsx
- src/components/PostList.jsx

Issue #28 also gives some context of where and how the avatars are being displayed for each card. 

It is important that you read the [CONTRIBUTING.md](https://github.com/open-sauced/.github/blob/09ed85f8482c392af87d76b356bf98f2aee1eeaa/CONTRIBUTING.md#issues) to learn how to assign yourself to the issue. Assigning yourself to the issue lets others know that somebody is actively working on the issue.

**Comment by bdougie** [comment]
@frankiefab100 do you want to take on this issue?

**Comment by frankiefab100** [comment]
Not yet

**Comment by kelvinsekx** [comment]
If @frankiefab100 isn't available, may be I should take this?

**Comment by hokagedemehin** [comment]
.take
