### ISSUE TITLE
Feature: Replace the removed contributor avatars 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#333]
### Type of feature

🍕 Feature

### Current behavior

During work on https://github.com/open-sauced/hot/pull/321 I had to remove the contributor avatars while that data s being added to the API. When it is available, we can added them back. 

![Screen Shot 2022-10-04 at 10 33 28 AM](https://user-images.githubusercontent.com/5713670/193887513-14ee8827-86ab-4a2a-8b62-0df81062653b.png)

### Suggested solution

uncommented the <StackedAvatars /> components in the app. 

### Additional context

https://github.com/open-sauced/hot/pull/321

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Contributions are available from this endpoint
```
/v1/repos/{owner}/{repo}/contributions
```

**Comment by Deadreyo** [comment]
> Contributions are available from this endpoint
> 
> ```
> /v1/repos/{owner}/{repo}/contributions
> ```

in beta, contributors are retrieved from the repo data object

``` const { id, full_name, name, description, issues, stars, contributions } = repo!;```

Shouldn't I do that in alpha as well instead of calling the api endpoint?

**Comment by bdougie** [comment]
We are actively trying to move away from that. Also between the time, I assigned this and now, my changes on alpha have been overwritten. What you are looking at is us leveraging the Supabase SDK, which is limited. 

## the new task
Instead of working on this, could re-do the changes linked in this issue first. https://github.com/open-sauced/hot/issues/380

Forget about working on alpha for now. Instead, work from beta.

**Comment by Deadreyo** [comment]
@bdougie 
in Hero.tsx, repositories are fetched and cards are dynamically created for it, all in the same files. This makes it very hard to dynamically get the contributors data from the api, since it will need an array of dynamic `useSWR` hooks, or even an array of `fetch` requests then storing the results and mapping them to their correct objects.

So I have 2 ways in mind:
1- Using the `contributors` field in repo's data (but you said you are trying to move away from that)
2- Make the cards into their own components, named HeroCard component, and then I will be able to manage api calls and use hooks dynamically much more easier.

Thoughts?
