### ISSUE TITLE
bug: downvoting a repo in myVotes list does not remove it from ui

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#416]
### Describe the bug

If you are in MyVotes section and you press on the upvote/voted
list from My voted Repository

### Steps to reproduce

1. Go to the hot app
2. MyVotes section
3. Press upvote/voted
4. look in My voted Repository it still remains behind

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Do you mean after up or down voting, the repository remains in the list of voted repos?
If so, you could adjust the title to something more relevant like "bug: downvoting a repo in myVotes list does not remove it from ui" 🍕

**Comment by NsdHSO** [comment]
> Do you mean after up or down voting, the repository remains in the list of voted repos? If so, you could adjust the title to something more relevant like "bug: downvoting a repo in myVotes list does not remove it from ui" 🍕

yes, this is the issue, Tnx for your help.

**Comment by bdougie** [comment]
> @bdougie GFI?

Not quite. This still needs more info and an attempt at a suggested solution. My guess is that the votes hooks need to refetch the votes when the button is clicked. 

https://github.com/open-sauced/hot/blob/2d5bb0d9f694ea630030c56bc6c2985cf231e9b3/src/hooks/useVotedRepos.ts#L23

**Comment by rajat4984** [comment]
Is this issue resolved?

**Comment by Alexandre-Lustosa-Escossio** [comment]
I'll try to .take this one

**Comment by Alexandre-Lustosa-Escossio** [comment]
Since I didn't have any pictures of the issue I tried going straight to the site and reproducing it. It turns out I'm not able to upvote any repository from any page. With further investigation, I found that the post call is returning 409 and apparently it's a problem in the database's schema so It might be nothing wrong with the code. 
![image](https://github.com/open-sauced/hot/assets/77128459/5754191f-3722-4159-ad76-8d4e22e3ca0c)
![image](https://github.com/open-sauced/hot/assets/77128459/48907f58-b05d-477f-9c51-6108fa5021d9)
Could someone help me understand if I'm going in the right direction?

**Comment by takanome-dev** [comment]
After you upvote or downvote a repo, the voted repos should be refetched and the UI updated.

But I think there is an issue in the [API](https://github.com/open-sauced/api) we need to address. See https://github.com/open-sauced/api/issues/122

Feel free to give it a try and let us know how it goes :slightly_smiling_face:

**Comment by Alexandre-Lustosa-Escossio** [comment]
Hey guys, since my time is short and I can't tackle the backend issues that avoid me from solving this one I'll leave this one open for someone who has more free time!

**Comment by JDGuillaume** [comment]
Would love to jump in on this one. New to open source, but I've worked with React previously.

Based on the traffic listed in the `Network` tab, it appears that the page is essentially DDoSing the provided Supabase endpoint. On the initial payload, I'm observing approximately 112 requests to the database. Without interacting with the page, the number of requests to Supabase are continuing to grow.

I think that the `useEffect` dependency in the `RepoList` component may be to blame. With JavaScript, using objects within the dependency array can trigger an infinite rendering loop due to how equality is calculated under the hood. It looks like one workaround is to use `JSON.stringify` to create a string value that is comparable from render to render. 

It's likely that this is a solved problem, but determining so would require further research. 

Here's a relevant Stack Overflow [post](https://stackoverflow.com/questions/59467758/passing-array-to-useeffect-dependency-list).
