### ISSUE TITLE
fix: repo not found [oven-sh/bun]

### ISSUE THREAD

**Issue by cjfinnell** [open-sauced/hot#425]
When loading https://hot.opensauced.pizza/ I see:
![Screen Shot 2022-12-09 at 08 36 12](https://user-images.githubusercontent.com/5659158/206737775-31c84bbe-4c31-45af-812c-d76a44b77876.png)

Network shows `404`s abound!

**Comment by NsdHSO** [comment]
@0-vortex please take a look

**Comment by 0-vortex** [comment]
> @0-vortex please take a look

Sorry for not answering earlier, due to how actions crawls over existing user stars in app.openauced, we were iterating over the user installation ids and re-creating the repository object without fetching all of the data again from the github api - this caused the `oven-sh/bun` repo to appear as `Jarred-Sumner/bun`. This error occurs in https://github.com/open-sauced/actions/blob/main/hot-supabase/user-stars.js#L176

A permanent fix for this will come soon, however, to protect ourselves from this kind of issue, we should have the top 3 promoted repositories listed by github id instead of full name! 😅 🍕

**Comment by cjfinnell** [comment]
Checked again today and the observed issue is taken care of - thanks!

<img width="1272" alt="Screen Shot 2022-12-16 at 09 12 36" src="https://user-images.githubusercontent.com/5659158/208141229-a3550937-9667-45a6-99f0-b856da030d65.png">

**Comment by mtfoley** [comment]
@0-vortex would a feasible fix to what you described involve changing these lines so that they use the `fetchedRepo` variable rather than the full name that was the basis of fetching? Since the rest API redirects, seems like this could be fixed on the fly, and all of the other properties used the `fetchedRepo` variable.
https://github.com/open-sauced/actions/blob/main/hot-supabase/user-stars.js#L194-L195
