### ISSUE TITLE
Infinite scroll and incremental data loads.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#81]
After some research, I think this can be completed as an infinite scroll and incremental data loads.

https://medium.com/suyeonme/react-how-to-implement-an-infinite-scroll-749003e9896a

_Originally posted by @bdougie in https://github.com/open-sauced/hot/issues/38#issuecomment-1001190510_

**Comment by bdougie** [comment]
Here is a thread from Twitter on the idea in React https://twitter.com/palashv2/status/1450807515835371522

**Comment by kelvinsekx** [comment]
I am particularly familiar with react window...from when it started with a different package name and all.

However, it doesn't work as infinite scroll...in my opinion the way we use redux and all.

With react window, we fetch all the data, map it to a list-like component and trust it to render to the Dom as much as the view port could cover.

If fetching all the data would cost next to fraction, then we could go with react window.

**Comment by 0-vortex** [comment]
In real life, infinite scroll does not work. Padding a page, the further away we are from the start, the less performant it will be, and the more we want to fix that we would be moving further away from the "infinite scroll part". The only way infinite scroll works is if it just scrolls infinitely while removing un-padded data on forward or backward scrolling.

Example:
- list scroll min height 120px
- screen height 980px -> 10 items padding
- 1 page is 10 items so we pad 3 pages

User scrolls on page 1, he needs data available for page 2 and 3 because of his screen height. When they get to page 2, we need to fetch data up to page 4, but when they get to page 4 we are removing page 1 from the dom - this is SEO friendly and performant, assuming we cache the GETs (scrolling back and forth through already fetched data would be instant).

^ This has A LOT of issues, the scrolling component itself not being one of them 🔮 😭

**Comment by bdougie** [comment]
We have discovered a work around with the "load more" button
